# Generated by Django 5.1.2 on 2024-10-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
