# Generated by Django 5.1.2 on 2024-10-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('archived', 'Archived'), ('published', 'Published'), ('draft', 'Draft')], default='archived', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='matrix', max_length=255),
        ),
    ]
